version: '3.8'

services:
  springboot-app:
    build: .
    container_name: springboot-app
    ports:
      - "8080:8080"
    depends_on:
      - assessment-api
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - app-network

  assessment-api:
    image: mrksdh/assessment:latest
    container_name: assessment-api
    ports:
      - "8081:8080"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
